---
# tasks file for cyhy_logrotate

- name: Install logrotate
  package:
    name: logrotate

# Setting backrefs to yes stops lineinfile from appending the line to
# the end of the file if the regex doesn't match
- name: Turn on compression globally for rotated logs
  lineinfile:
    dest: /etc/logrotate.conf
    regexp: '^#compress'
    state: present
    line: compress
    backrefs: yes

- name: Install cyhy logrotate configuration
  copy:
    src: cyhy
    dest: /etc/logrotate.d/cyhy
    mode: 0644
