---
- name: Import upgrade playbook
  ansible.builtin.import_playbook: upgrade.yml

- name: Import python playbook
  ansible.builtin.import_playbook: python.yml

# rsyslog is installed anywhere we would be applying this Ansible role
- name: Install rsyslog
  hosts: all
  tasks:
    # This is required temporarily, because of
    # https://github.com/ansible/ansible/issues/56583
    - name: Temporary workaround for ansible/ansible#56583
      ansible.builtin.set_fact:
        ansible_facts:
          pkg_mgr: yum
      when: ansible_os_family == "RedHat" and ansible_distribution == "Amazon"
    - name: Install rsyslog
      ansible.builtin.package:
        name:
          - rsyslog
